import { routing } from "@/i18n/routing";
import "@unocss/reset/tailwind.css";
import "../../styles/globals.css";
import { type Metadata } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import { notFound } from "next/navigation";

const roboto = Roboto({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["300", "400", "500", "700"],
});

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;

  return {
    description:
      locale === "ar"
        ? "تم إنشاؤه بواسطة تطبيق نكست"
        : "Generated by create next app",
    title: locale === "ar" ? "تطبيق نكست" : "Create Next App",
  };
}

// eslint-disable-next-line unicorn/prevent-abbreviations
export const generateStaticParams = async () => {
  return routing.locales.map((locale) => ({
    locale,
  }));
};

export default async function LocaleLayout({
  children,
  params,
}: {
  readonly children: React.ReactNode;
  readonly params: Promise<{ locale: string }>;
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      className={roboto.variable}
      dir={locale === "ar" ? "rtl" : "ltr"}
      lang={locale}
      suppressHydrationWarning
    >
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
